### ISSUE TITLE
example

### ISSUE THREAD

**Issue by alveflo** [alveflo/yake#1]
``` yaml
init:
    description: Initializing project
    question: Application name
    before:
        - clone
    commands:
        - npm install
        - bower install
    after:
        - gulp

clone:
    description: Cloning project...
    commands:
        - git clone <some repo>

gulp:
    description: Starting gulp
    commands:
        - gulp
```

=>

```
$ yake init
yake: Running task "init"
------------------------------------------------
? Application name:
> foobar
yake: [clone] Cloning project...
yake: [init] Initializing project
yake: [gulp] Starting gulp
------------------------------------------------
yake: Done. Elapsed time 00:01:42
```
